/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 최근 작업 목록 */
        get: operations["listJobs"];
        put?: never;
        /**
         * 새 작업 생성
         * @description YouTube 영상 URL을 받아 작업을 생성한다. 동일 영상 ID의 기존 작업이
         *     존재하면 신규 생성 없이 해당 작업을 재사용해 200으로 응답한다.
         */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** 작업 상세 */
        get: operations["getJob"];
        put?: never;
        post?: never;
        /**
         * 작업 취소 또는 영구 삭제
         * @description 상태에 따라 분기 동작한다 — 클라이언트는 분기 처리 불필요.
         *
         *     - **진행 중** (`pending`, `downloading`, `subtitle_processing`,
         *       `translating`, `rendering`): cancel 시맨틱 — `failed` / `USER_CANCELLED`
         *       마킹 + `var/storage/<job_id>/` 산출물 purge. DB row 는 보존.
         *       spec FR-028 (Clarifications 2026-05-27).
         *     - **종결** (`completed`, `failed`): hard delete — storage purge + DB row
         *       영구 제거 (cascade 로 SubtitleTrack / Cue / Asset / JobEvent 등 함께 제거).
         *       spec FR-030a (Clarifications 2026-05-28).
         *
         *     응답 envelope `data.action` 으로 어떤 동작이 일어났는지 구분 (`cancelled` |
         *     `deleted`). 그 외 `data` 키는 VideoJob 필드와 동일.
         */
        delete: operations["cancelOrDeleteJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/subtitles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** cue 목록 조회 (원문 / 번역 동시) */
        get: operations["getSubtitles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** dual subtitle 파일 다운로드 */
        get: operations["downloadDualSubtitle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/video": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /**
         * 영상 스트리밍
         * @description HTTP Range 헤더 지원
         */
        get: operations["streamVideo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /**
         * 실시간 작업 이벤트 (SSE)
         * @description Server-Sent Events 스트림. 이벤트 타입 및 payload 스키마는
         *     contracts/events.md 참고.
         */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        JobStatus: "pending" | "downloading" | "subtitle_processing" | "translating" | "rendering" | "completed" | "failed";
        /** @enum {string} */
        Language: "ko" | "ja";
        CreateJobRequest: {
            /**
             * Format: uri
             * @description YouTube 단일 영상 URL
             * @example https://www.youtube.com/watch?v=abcdefghijk
             */
            url: string;
        };
        VideoMetadata: {
            title: string | null;
            channel: string | null;
            /**
             * Format: uri
             * @description YouTube 채널 페이지 URL — UI 채널명 링크에 사용
             * @example https://www.youtube.com/@example
             */
            channel_url: string | null;
            duration_sec: number | null;
            /** @enum {string|null} */
            subtitle_source: "manual" | "auto" | null;
        };
        Job: {
            /** Format: ulid */
            id: string;
            /** Format: uri */
            source_url: string;
            youtube_video_id: string;
            source_language?: components["schemas"]["Language"] | null;
            target_language?: components["schemas"]["Language"] | null;
            status: components["schemas"]["JobStatus"];
            /** @description 현재 단계의 0~1 진행률 (단계 전이 시 0으로 리셋) */
            progress?: number | null;
            error_stage?: string | null;
            error_code?: string | null;
            error_message?: string | null;
            metadata: components["schemas"]["VideoMetadata"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            /** @description 동일 URL의 기존 작업이 재사용되었는지 여부 (생성 시 응답에만 의미 있음) */
            reused: boolean;
        };
        JobEnvelope: {
            success: boolean;
            data?: components["schemas"]["Job"];
            error?: components["schemas"]["ErrorBody"];
            request_id: string;
        };
        /**
         * @description DELETE /jobs/{job_id} 응답에서 어떤 동작이 일어났는지 표시.
         *     - cancelled: 진행 중 작업이 USER_CANCELLED 로 마킹됨 (DB row 보존)
         *     - deleted:   종결 작업이 영구 삭제됨 (DB row + 산출물 제거)
         * @enum {string}
         */
        JobAction: "cancelled" | "deleted";
        /**
         * @description DELETE /jobs/{job_id} 전용 envelope. data 는 VideoJob 필드 + action 을 포함한다
         *     (backward compatible — 기존 JobEnvelope 호출자도 status / id 등을 그대로 사용 가능).
         */
        JobActionEnvelope: {
            success: boolean;
            data?: components["schemas"]["Job"] & {
                action: components["schemas"]["JobAction"];
            };
            error?: components["schemas"]["ErrorBody"];
            request_id: string;
        };
        JobListEnvelope: {
            success: boolean;
            data?: {
                items: components["schemas"]["Job"][];
                next_cursor?: string | null;
            };
            error?: components["schemas"]["ErrorBody"];
            request_id: string;
        };
        SubtitleCue: {
            sequence: number;
            start_ms: number;
            end_ms: number;
            text: string;
        };
        SubtitleBundle: {
            /** Format: ulid */
            job_id: string;
            source_language: components["schemas"]["Language"];
            target_language: components["schemas"]["Language"];
            source_cues: components["schemas"]["SubtitleCue"][];
            translated_cues: components["schemas"]["SubtitleCue"][];
            total: number;
            offset: number;
            limit: number;
        };
        SubtitleBundleEnvelope: {
            success: boolean;
            data?: components["schemas"]["SubtitleBundle"];
            error?: components["schemas"]["ErrorBody"];
            request_id: string;
        };
        ErrorBody: {
            /**
             * @description 기계 판독용 코드. 카테고리:
             *       - INVALID_URL, INVALID_INPUT
             *       - NOT_FOUND
             *       - CONFLICT, ILLEGAL_STATE
             *       - SUBTITLE_NOT_FOUND, SUBTITLE_LANGUAGE_UNSUPPORTED
             *       - DOWNLOAD_FAILED, TRANSLATION_FAILED, RENDER_FAILED
             *       - RATE_LIMITED
             *       - USER_CANCELLED
             *       - INTERNAL_ERROR
             */
            code: string;
            /** @description 사용자 친화적 메시지(한국어) */
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            error: components["schemas"]["ErrorBody"];
            request_id: string;
        };
    };
    responses: {
        /** @description 입력 검증 실패 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 리소스 없음 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 상태 불일치 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 너무 잦은 요청 */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        JobId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listJobs: {
        parameters: {
            query?: {
                limit?: number;
                /** @description 다음 페이지 cursor (created_at 기반) */
                cursor?: string | null;
                status?: components["schemas"]["JobStatus"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListEnvelope"];
                };
            };
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description 기존 작업 재사용 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnvelope"];
                };
            };
            /** @description 신규 작업 생성됨 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelOrDeleteJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 취소 또는 삭제 처리됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobActionEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSubtitles: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtitleBundleEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description 작업이 아직 번역 완료되지 않음 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    downloadDualSubtitle: {
        parameters: {
            query: {
                format: "srt" | "vtt";
                order?: "source-first" | "target-first";
            };
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 다운로드 가능 */
            200: {
                headers: {
                    /** @description attachment; filename=... */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/x-subrip": unknown;
                    "text/vtt": unknown;
                };
            };
            404: components["responses"]["NotFound"];
            /** @description 작업이 아직 완료되지 않음 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    streamVideo: {
        parameters: {
            query?: never;
            header?: {
                Range?: string;
            };
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 전체 파일 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "video/mp4": unknown;
                };
            };
            /** @description Partial Content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "video/mp4": unknown;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 이벤트 스트림 (text/event-stream) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
